version: '3.8'

services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
    command: pnpm run start:dev backend-api
    volumes:
      - .:/app
      - /app/node_modules
